spring:
  datasource:
  url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:healthcare_db}
  username: ${POSTGRES_USER:healthcare}
  password: ${POSTGRES_PASSWORD:mile}


  jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect


  spring:
    profiles:
      active: pg